### ISSUE TITLE
Could you add requirements for the repo?

### ISSUE THREAD

**Issue by liyang619** [btx0424/OmniDrones#28]
I have a question about torchrl when i run train.py as:
ImportError: cannot import name '_replace_last' from 'torchrl.envs.utils'

I have tried install all versions of torchrl as list in pip website, but cannot solve it.

**Comment by btx0424** [comment]
Thanks for reporting. The recommended way for installing TorchRL is through GitHub because the versions published on Pypi could lag behind the development branch. I will fix the setup of `TensorSpec`s for most of the tasks to make things compatible with a [recent update](https://github.com/pytorch/rl/pull/1539) in the next few days.

**Comment by btx0424** [comment]
@liyang619 Hello there, I have updated the `TensorSpec`s. TorchRL also released its 0.2.0. Things should be working now.
